package app.sanctuary.api.asksanctuary.model;

public enum AskSanctuaryIntent {
    PRAYER_REQUEST,
    LIFE_CONCERN,
    GRIEF,
    FAMILY_HEALTH_CONCERN,
    RELATIONSHIP_CRISIS,
    WORK_OR_DISCERNMENT,
    GRATITUDE,
    CATHOLIC_QUESTION,
    SCRIPTURE_HELP,
    NOT_SPIRITUAL_OR_IRRELEVANT,
    VIOLENCE_RISK,
    SELF_HARM_RISK,
    EMERGENCY_OR_MEDICAL,
    ABUSE_OR_DANGER
}
