spring:
  datasource:
    url: ${SANCTUARY_DB_URL}
    username: ${SANCTUARY_DB_USERNAME}
    password: ${SANCTUARY_DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SANCTUARY_COGNITO_ISSUER_URI:}

server:
  port: ${SANCTUARY_API_PORT:8080}

sanctuary:
  auth:
    enabled: ${SANCTUARY_AUTH_ENABLED:false}
    audience: ${SANCTUARY_COGNITO_CLIENT_ID:}
