package app.sanctuary.android.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import java.time.LocalDate
import java.time.YearMonth
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.util.Locale

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val locale: Locale
) {
    English("en", "English", Locale("en", "US")),
    Spanish("es", "Español", Locale("es", "ES")),
    Polish("pl", "Polski", Locale("pl", "PL"));

    companion object {
        fun fromCode(raw: String?): AppLanguage = when (raw?.lowercase()) {
            "es" -> Spanish
            "pl" -> Polish
            else -> English
        }
    }
}

class SanctuaryStrings(
    val language: AppLanguage
) {
    private val strings: Map<String, String>
        get() = when (language) {
            AppLanguage.English -> english
            AppLanguage.Spanish -> spanish
            AppLanguage.Polish -> polish
        }

    fun t(key: String): String = strings[key] ?: english[key] ?: key

    fun weekdaySymbolsShort(): List<String> = listOf(
        t("weekday.sun"),
        t("weekday.mon"),
        t("weekday.tue"),
        t("weekday.wed"),
        t("weekday.thu"),
        t("weekday.fri"),
        t("weekday.sat")
    )

    fun formatMonthYear(month: Int, year: Int): String {
        val ym = YearMonth.of(year, month)
        val formatter = DateTimeFormatter.ofPattern("MMMM yyyy", language.locale)
        return ym.atDay(1).format(formatter)
    }

    fun formatMonthDayYear(date: LocalDate): String {
        val formatter = DateTimeFormatter.ofPattern("MMMM d, yyyy", language.locale)
        return date.format(formatter)
    }

    fun localizedDailyReadingsUrl(raw: String?): String {
        val landing = when (language) {
            AppLanguage.Spanish -> "https://bible.usccb.org/es/daily-bible-reading"
            else -> "https://bible.usccb.org/daily-bible-reading"
        }
        val value = raw?.takeIf { it.isNotBlank() } ?: return landing
        if (language != AppLanguage.Spanish) return value
        return when {
            value.contains("/es/") -> value
            value.startsWith("https://bible.usccb.org/bible/readings/") ->
                value.replace(
                    "https://bible.usccb.org/bible/readings/",
                    "https://bible.usccb.org/es/bible/lecturas/"
                )
            value == "https://bible.usccb.org/daily-bible-reading" -> landing
            value == "https://bible.usccb.org/" -> landing
            else -> value
        }
    }

    private companion object {
        val english = mapOf(
            "tab.home" to "Home",
            "tab.novenas" to "Novenas",
            "tab.liturgical" to "Liturgical",
            "tab.saints" to "Saints",
            "tab.me" to "Me",
            "common.today" to "Today",
            "common.day" to "Day",
            "common.week" to "Week",
            "common.month" to "Month",
            "common.close" to "Close",
            "common.cancel" to "Cancel",
            "common.back" to "Back",
            "common.loading" to "Preparing Sanctuary...",
            "common.openDetails" to "Open details",
            "common.search" to "Search",
            "weekday.sun" to "Sun",
            "weekday.mon" to "Mon",
            "weekday.tue" to "Tue",
            "weekday.wed" to "Wed",
            "weekday.thu" to "Thu",
            "weekday.fri" to "Fri",
            "weekday.sat" to "Sat",
            "home.about" to "About Sanctuary",
            "home.language" to "Language",
            "home.chooseLanguage" to "Choose language",
            "home.eyebrow" to "#1 Catholic Prayer Companion",
            "home.welcome" to "Welcome to your sanctuary",
            "home.connect" to "Find daily readings, pray the Rosary, or search saints, novenas, prayers, and intentions from the paths below.",
            "home.supporting" to "Use the tabs to explore the liturgical calendar, saint feast days, and novena schedule.",
            "home.saints" to "Saints",
            "home.saintsSubtitle" to "Feasts and biographies",
            "home.novenas" to "Novenas",
            "home.novenasSubtitle" to "Journeys of prayer",
            "home.prayers" to "Prayers",
            "home.prayersSubtitle" to "Daily essentials",
            "home.rosary" to "Rosary",
            "home.rosarySubtitle" to "Mysteries by day",
            "home.daily" to "Daily",
            "home.dailySubtitle" to "Daily readings",
            "home.intentions" to "Intentions",
            "home.intentionsSubtitle" to "Search by need",
            "home.liturgical" to "Liturgical",
            "home.liturgicalSubtitle" to "Follow the Church calendar",
            "calendar.subtitle.novenas" to "Novenas • Tap to jump",
            "calendar.subtitle.liturgical" to "Liturgical • Tap to jump",
            "calendar.subtitle.saints" to "Saints • Tap to jump",
            "calendar.searchSaints" to "Search Saints",
            "calendar.searchNovenas" to "Search Novenas",
            "calendar.searchIntentions" to "Search Novena Intentions",
            "calendar.openDailyReadings" to "Open daily readings",
            "search.saintsTitle" to "Search Saints",
            "search.novenasTitle" to "Search Novenas",
            "search.prayersTitle" to "Search Prayers",
            "search.rosaryTitle" to "Search Rosary",
            "search.intentionsTitle" to "Search Novena Intentions",
            "search.field" to "Search",
            "auth.account" to "Account",
            "auth.androidTitle" to "Sanctuary for Android",
            "auth.androidIntro" to "This first Android build is focused on auth parity and live Sanctuary content, so we can distribute something real to the dev track today.",
            "auth.accountBody" to "Log in or create an account to sync your saved saints, novenas, prayers, and progress.",
            "auth.login" to "Login",
            "auth.register" to "Register",
            "auth.signInCalmly" to "Sign in calmly",
            "auth.createAccount" to "Create your account",
            "auth.confirmAccount" to "Confirm your account",
            "auth.resetCalmly" to "Reset your password calmly",
            "auth.chooseNewPassword" to "Choose a new password",
            "auth.email" to "Email",
            "auth.password" to "Password",
            "auth.confirmPassword" to "Confirm password",
            "auth.firstName" to "First name",
            "auth.lastName" to "Last name",
            "auth.code" to "Confirmation code",
            "auth.forgotPassword" to "Forgot password?",
            "auth.verificationCode" to "Verification code",
            "auth.resetCode" to "Reset code",
            "auth.newPassword" to "New password",
            "auth.confirmNewPassword" to "Confirm new password",
            "auth.back" to "Back",
            "auth.returning" to "Returning to Sanctuary",
            "auth.returningBody" to "Sign in to your saved saints, novenas, prayers, and progress.",
            "auth.newToSanctuary" to "New to Sanctuary",
            "auth.newToSanctuaryBody" to "Create a free account so this Android build can sync with your existing Sanctuary account.",
            "auth.createAccountCta" to "Create account",
            "auth.confirmAccountCta" to "Confirm account",
            "auth.sendNewCode" to "Send a new code",
            "auth.sendResetCode" to "Send reset code",
            "auth.saveNewPassword" to "Save new password",
            "auth.sendNewResetCode" to "Send a new reset code",
            "auth.passwordStrength" to "Password strength",
            "auth.passwordsMustMatchCreate" to "Passwords must match before you can create the account.",
            "auth.passwordsMustMatchSave" to "Passwords must match before you can save the new password.",
            "auth.passwordsMatch" to "Passwords match.",
            "auth.passwordStrengthReady" to "Ready",
            "auth.passwordStrengthAlmost" to "Almost there",
            "auth.passwordStrengthNeedsWork" to "Needs work",
            "auth.passwordStrengthTooWeak" to "Too weak",
            "auth.rule.length" to "At least 10 characters",
            "auth.rule.upper" to "One uppercase letter",
            "auth.rule.lower" to "One lowercase letter",
            "auth.rule.number" to "One number",
            "auth.confirmationSentPrefix" to "We sent a confirmation code to",
            "auth.resetSentPrefix" to "We sent a reset code to",
            "status.registerTimeout" to "Sanctuary took too long to register. Please try again.",
            "status.confirmTimeout" to "Sanctuary took too long to confirm your account. Please try again.",
            "status.resendTimeout" to "Sanctuary took too long to resend the confirmation code. Please try again.",
            "status.forgotTimeout" to "Sanctuary took too long to start password reset. Please try again.",
            "status.resetTimeout" to "Sanctuary took too long to reset your password. Please try again.",
            "status.loginTimeout" to "Sanctuary took too long to sign you in. Please try again.",
            "status.deleteAccountTimeout" to "Sanctuary took too long to delete your account. Please try again.",
            "status.deleteAccountFailed" to "We could not delete your account right now. Please try again.",
            "status.remindersUpdated" to "Your reminder preferences are updated.",
            "status.remindersOff" to "Prayer reminders are off.",
            "me.title" to "Me",
            "me.subtitle" to "Your novenas in progress and saved favorites.",
            "me.signedIn" to "Signed in",
            "me.accountSummary" to "Your favorites, active novenas, and future account settings live here.",
            "me.accountFallback" to "Sanctuary account",
            "me.reminders" to "Reminders",
            "me.inProgress" to "Novenas in Progress",
            "me.favoriteNovenas" to "Favorite Novenas",
            "me.favoriteSaints" to "Favorite Saints",
            "me.favoritePrayers" to "Favorite Prayers",
            "me.noInProgress" to "No novenas in progress.",
            "me.noneFavoriteNovenas" to "No favorite novenas yet.",
            "me.noneFavoriteSaints" to "No favorite saints yet.",
            "me.noneFavoritePrayers" to "No favorite prayers yet.",
            "me.logout" to "Logout",
            "me.deleteAccount.title" to "Delete account",
            "me.deleteAccount.body" to "Permanently delete your Sanctuary account, favorites, novena progress, and preferences.",
            "me.deleteAccount.action" to "Delete my account",
            "me.deleteAccount.deleting" to "Deleting account...",
            "me.deleteAccount.confirmTitle" to "Delete your account?",
            "me.deleteAccount.confirmBody" to "This permanently removes your Sanctuary account and saved app data. This cannot be undone.",
            "me.deleteAccount.confirmAction" to "Delete account",
            "me.metric.activeNovenas" to "Active novenas",
            "me.metric.favoriteNovenas" to "Favorite novenas",
            "me.metric.favoriteSaints" to "Favorite saints",
            "me.metric.favoritePrayers" to "Favorite prayers",
            "me.metric.environment" to "Environment",
            "reminder.novenas" to "Novenas in progress",
            "reminder.novenasBody" to "Send morning and evening reminders when you have a novena in progress.",
            "reminder.daily" to "Once-daily Sanctuary reminder",
            "reminder.dailyBody" to "Send a gentle morning reminder when you do not have a novena in progress.",
            "about.title" to "About Sanctuary",
            "about.subtitle" to "Sanctuary is a Catholic companion for prayer, daily readings, saints, liturgical living, and novenas.",
            "about.desktopVersion" to "Use Sanctuary on desktop",
            "about.desktopBody" to "You can also use Sanctuary on desktop for the full web experience, including daily readings, saints, liturgical browsing, novenas, and your synced account.",
            "about.versionTitle" to "App version",
            "about.versionLabel" to "Version",
            "about.buildLabel" to "Build",
            "about.environmentLabel" to "Environment",
            "about.whatsInApp" to "What's in the app",
            "about.references" to "References",
            "about.contact" to "Contact & feedback",
            "about.link.desktop" to "Open mydailysanctuary.com",
            "about.link.support" to "Support",
            "about.link.privacy" to "Privacy Policy",
            "about.whatsInApp.liturgical" to "Liturgical: day, week, and month calendar views with season context and direct daily readings links.",
            "about.whatsInApp.saints" to "Saints: date-aware saint listings, detailed profiles, and searchable content.",
            "about.whatsInApp.novenas" to "Novenas: rule-based start dates, end-date tracking, intentions search, and progress management.",
            "about.referencesBody" to "Sanctuary currently references these public sources for readings and saint information.",
            "about.reference.usccb" to "USCCB (daily readings)",
            "about.reference.wikipedia" to "Wikipedia",
            "about.contactBody" to "To report bugs, request corrections, or send feedback, contact us and include the page or feature you were using along with a short description of the issue.",
            "about.emailSupport" to "Email Support",
            "about.supportTitle" to "Support",
            "about.privacyTitle" to "Privacy Policy",
            "about.brand" to "Sanctuary",
            "about.link.usccb" to "USCCB Daily Bible Reading",
            "about.link.wikipedia" to "Wikipedia",
            "about.copyright" to "Sanctuary © 2026. All rights reserved.",
            "about.supportSubtitle" to "Support and feedback for Sanctuary.",
            "about.privacySubtitle" to "Effective date: April 13, 2026",
            "about.support.section.help" to "Help and Feedback",
            "about.support.body.help" to "If you need help with Sanctuary, have a bug to report, or want to suggest an improvement, contact us at info@mydailysanctuary.com and include your device type, platform, and a short description of the issue.",
            "about.support.section.features" to "App Features",
            "about.support.body.features" to "Sanctuary includes Catholic prayers, novenas, saint reflections, liturgical calendar content, and optional reminders to support prayer throughout the day.",
            "about.support.section.response" to "Response Time",
            "about.support.body.response" to "We do our best to respond to support requests promptly.",
            "about.privacy.section.collect" to "Information We Collect",
            "about.privacy.body.collect" to "Sanctuary is designed to work primarily with local content on your device. We do not require account creation to use the app.",
            "about.privacy.section.location" to "Location",
            "about.privacy.body.location" to "If you choose to use location-aware features, Sanctuary may request location access to improve nearby content and time-sensitive experiences.",
            "about.privacy.section.notifications" to "Notifications",
            "about.privacy.body.notifications" to "If you choose to allow notifications, Sanctuary uses notification permissions to send reminder notifications for prayer and novena activity. Notifications are optional and can be disabled at any time in your device settings.",
            "about.privacy.section.sharing" to "Sharing",
            "about.privacy.body.sharing" to "Sanctuary does not sell your personal information. We use trusted providers only where needed to support core app functionality.",
            "about.privacy.section.choices" to "Your Choices",
            "about.privacy.body.choices" to "You can use most of Sanctuary without creating an account, and you can remove app data from your device at any time.",
            "about.privacy.section.contact" to "Contact",
            "about.privacy.body.contact" to "If you have privacy questions, contact us at info@mydailysanctuary.com.",
            "calendar.dailyReadingsTitle" to "Daily Readings",
            "calendar.dailyReadingsSubtitle" to "USCCB readings inside Sanctuary",
            "calendar.chooseDay" to "Choose Day",
            "calendar.dayLabel" to "Day",
            "calendar.dayNumberPrefix" to "Day",
            "calendar.noNovenaStarting" to "Sanctuary does not have a novena starting on this day.",
            "calendar.noLiturgicalFound" to "No liturgical reading found",
            "calendar.noLiturgicalBody" to "Sanctuary did not return a liturgical observance for this day yet.",
            "calendar.dailyReadingsMissing" to "Sanctuary could not find today's USCCB reading link right now.",
            "calendar.dailyReadingsOpenError" to "Sanctuary could not open today's readings right now.",
            "detail.loadErrorTitle" to "Could not load this right now",
            "detail.loadErrorBody" to "Sanctuary could not complete that request right now.",
            "detail.favorite.add" to "Add to Favorites",
            "detail.favorite.saved" to "Saved to Favorites",
            "detail.summary" to "Summary",
            "detail.biography" to "Biography",
            "detail.sources" to "Sources",
            "detail.intentions" to "Intentions",
            "detail.startNovena" to "Start Novena",
            "detail.stopNovena" to "Stop Novena",
            "detail.completeDay" to "Complete Day",
            "detail.completed" to "Completed",
            "detail.loginToTrack" to "Log in or register to start this novena and track your progress.",
            "detail.noDayContent" to "No day content was found for this novena yet.",
            "detail.scripture" to "Scripture",
            "detail.prayer" to "Prayer",
            "detail.reflection" to "Reflection",
            "detail.content" to "Content",
            "detail.openingPrayer" to "Opening Prayer",
            "detail.meditation" to "Meditation",
            "detail.closingPrayer" to "Closing Prayer",
            "inline.loading" to "Loading…",
            "season.advent" to "Advent",
            "season.christmas" to "Christmas",
            "season.lent" to "Lent",
            "season.easter" to "Easter",
            "season.ordinary" to "Ordinary Time"
        )

        val spanish = mapOf(
            "tab.home" to "Inicio",
            "tab.novenas" to "Novenas",
            "tab.liturgical" to "Litúrgico",
            "tab.saints" to "Santos",
            "tab.me" to "Yo",
            "common.today" to "Hoy",
            "common.day" to "Día",
            "common.week" to "Semana",
            "common.month" to "Mes",
            "common.close" to "Cerrar",
            "common.cancel" to "Cancelar",
            "common.back" to "Volver",
            "common.loading" to "Preparando Sanctuary...",
            "common.openDetails" to "Abrir detalles",
            "common.search" to "Buscar",
            "weekday.sun" to "Dom",
            "weekday.mon" to "Lun",
            "weekday.tue" to "Mar",
            "weekday.wed" to "Mié",
            "weekday.thu" to "Jue",
            "weekday.fri" to "Vie",
            "weekday.sat" to "Sáb",
            "home.about" to "Sobre Sanctuary",
            "home.language" to "Idioma",
            "home.chooseLanguage" to "Elegir idioma",
            "home.eyebrow" to "#1 Compañero Católico de Oración",
            "home.welcome" to "Bienvenido a tu santuario",
            "home.connect" to "Encuentra las lecturas diarias, reza el Rosario o busca santos, novenas, oraciones e intenciones desde las opciones de abajo.",
            "home.supporting" to "Usa las pestañas para explorar el calendario litúrgico, las fiestas de santos y el calendario de novenas.",
            "home.saints" to "Santos",
            "home.saintsSubtitle" to "Fiestas y biografías",
            "home.novenas" to "Novenas",
            "home.novenasSubtitle" to "Caminos de oración",
            "home.prayers" to "Oraciones",
            "home.prayersSubtitle" to "Esenciales diarios",
            "home.rosary" to "Rosario",
            "home.rosarySubtitle" to "Misterios por día",
            "home.daily" to "Diario",
            "home.dailySubtitle" to "Lecturas diarias",
            "home.intentions" to "Intenciones",
            "home.intentionsSubtitle" to "Buscar por necesidad",
            "home.liturgical" to "Litúrgico",
            "home.liturgicalSubtitle" to "Sigue el calendario de la Iglesia",
            "calendar.subtitle.novenas" to "Novenas • Toca para saltar",
            "calendar.subtitle.liturgical" to "Litúrgico • Toca para saltar",
            "calendar.subtitle.saints" to "Santos • Toca para saltar",
            "calendar.searchSaints" to "Buscar santos",
            "calendar.searchNovenas" to "Buscar novenas",
            "calendar.searchIntentions" to "Buscar intenciones de novena",
            "calendar.openDailyReadings" to "Abrir lecturas diarias",
            "search.saintsTitle" to "Buscar santos",
            "search.novenasTitle" to "Buscar novenas",
            "search.prayersTitle" to "Buscar oraciones",
            "search.rosaryTitle" to "Buscar rosarios",
            "search.intentionsTitle" to "Buscar intenciones de novena",
            "search.field" to "Buscar",
            "auth.account" to "Cuenta",
            "auth.androidTitle" to "Sanctuary para Android",
            "auth.androidIntro" to "Esta primera compilación de Android se centra en la paridad de autenticación y el contenido en vivo de Sanctuary para que podamos distribuir algo real al entorno de desarrollo hoy.",
            "auth.accountBody" to "Inicia sesión o crea una cuenta para sincronizar tus santos, novenas, oraciones y progreso guardados.",
            "auth.login" to "Iniciar sesión",
            "auth.register" to "Registrarse",
            "auth.signInCalmly" to "Inicia sesión con calma",
            "auth.createAccount" to "Crea tu cuenta",
            "auth.confirmAccount" to "Confirma tu cuenta",
            "auth.resetCalmly" to "Restablece tu contraseña con calma",
            "auth.chooseNewPassword" to "Elige una nueva contraseña",
            "auth.email" to "Correo",
            "auth.password" to "Contraseña",
            "auth.confirmPassword" to "Confirmar contraseña",
            "auth.firstName" to "Nombre",
            "auth.lastName" to "Apellido",
            "auth.code" to "Código de confirmación",
            "auth.forgotPassword" to "¿Olvidaste tu contraseña?",
            "auth.verificationCode" to "Código de verificación",
            "auth.resetCode" to "Código de restablecimiento",
            "auth.newPassword" to "Nueva contraseña",
            "auth.confirmNewPassword" to "Confirmar nueva contraseña",
            "auth.back" to "Volver",
            "auth.returning" to "Volver a Sanctuary",
            "auth.returningBody" to "Inicia sesión para recuperar tus santos, novenas, oraciones y progreso guardados.",
            "auth.newToSanctuary" to "Nuevo en Sanctuary",
            "auth.newToSanctuaryBody" to "Crea una cuenta gratuita para que esta compilación de Android pueda sincronizarse con tu cuenta existente de Sanctuary.",
            "auth.createAccountCta" to "Crear cuenta",
            "auth.confirmAccountCta" to "Confirmar cuenta",
            "auth.sendNewCode" to "Enviar un nuevo código",
            "auth.sendResetCode" to "Enviar código de restablecimiento",
            "auth.saveNewPassword" to "Guardar nueva contraseña",
            "auth.sendNewResetCode" to "Enviar un nuevo código de restablecimiento",
            "auth.passwordStrength" to "Seguridad de la contraseña",
            "auth.passwordsMustMatchCreate" to "Las contraseñas deben coincidir antes de crear la cuenta.",
            "auth.passwordsMustMatchSave" to "Las contraseñas deben coincidir antes de guardar la nueva contraseña.",
            "auth.passwordsMatch" to "Las contraseñas coinciden.",
            "auth.passwordStrengthReady" to "Lista",
            "auth.passwordStrengthAlmost" to "Casi lista",
            "auth.passwordStrengthNeedsWork" to "Falta trabajo",
            "auth.passwordStrengthTooWeak" to "Muy débil",
            "auth.rule.length" to "Al menos 10 caracteres",
            "auth.rule.upper" to "Una letra mayúscula",
            "auth.rule.lower" to "Una letra minúscula",
            "auth.rule.number" to "Un número",
            "auth.confirmationSentPrefix" to "Enviamos un código de confirmación a",
            "auth.resetSentPrefix" to "Enviamos un código de restablecimiento a",
            "status.registerTimeout" to "Sanctuary tardó demasiado en registrarte. Inténtalo de nuevo.",
            "status.confirmTimeout" to "Sanctuary tardó demasiado en confirmar tu cuenta. Inténtalo de nuevo.",
            "status.resendTimeout" to "Sanctuary tardó demasiado en reenviar el código de confirmación. Inténtalo de nuevo.",
            "status.forgotTimeout" to "Sanctuary tardó demasiado en iniciar el restablecimiento de contraseña. Inténtalo de nuevo.",
            "status.resetTimeout" to "Sanctuary tardó demasiado en restablecer tu contraseña. Inténtalo de nuevo.",
            "status.loginTimeout" to "Sanctuary tardó demasiado en iniciar tu sesión. Inténtalo de nuevo.",
            "status.deleteAccountTimeout" to "Sanctuary tardó demasiado en eliminar tu cuenta. Inténtalo de nuevo.",
            "status.deleteAccountFailed" to "No pudimos eliminar tu cuenta en este momento. Inténtalo de nuevo.",
            "status.remindersUpdated" to "Tus preferencias de recordatorios se actualizaron.",
            "status.remindersOff" to "Los recordatorios de oración están desactivados.",
            "me.title" to "Yo",
            "me.subtitle" to "Tus novenas en progreso y favoritos guardados.",
            "me.signedIn" to "Sesión iniciada",
            "me.accountSummary" to "Tus favoritos, novenas activas y futuros ajustes de cuenta viven aquí.",
            "me.accountFallback" to "Cuenta de Sanctuary",
            "me.reminders" to "Recordatorios",
            "me.inProgress" to "Novenas en curso",
            "me.favoriteNovenas" to "Novenas favoritas",
            "me.favoriteSaints" to "Santos favoritos",
            "me.favoritePrayers" to "Oraciones favoritas",
            "me.noInProgress" to "No hay novenas en progreso.",
            "me.noneFavoriteNovenas" to "Aún no hay novenas favoritas.",
            "me.noneFavoriteSaints" to "Aún no hay santos favoritos.",
            "me.noneFavoritePrayers" to "Aún no hay oraciones favoritas.",
            "me.logout" to "Cerrar sesión",
            "me.deleteAccount.title" to "Eliminar cuenta",
            "me.deleteAccount.body" to "Elimina permanentemente tu cuenta de Sanctuary, favoritos, progreso de novenas y preferencias.",
            "me.deleteAccount.action" to "Eliminar mi cuenta",
            "me.deleteAccount.deleting" to "Eliminando cuenta...",
            "me.deleteAccount.confirmTitle" to "¿Eliminar tu cuenta?",
            "me.deleteAccount.confirmBody" to "Esto elimina permanentemente tu cuenta de Sanctuary y los datos guardados en la app. No se puede deshacer.",
            "me.deleteAccount.confirmAction" to "Eliminar cuenta",
            "me.metric.activeNovenas" to "Novenas activas",
            "me.metric.favoriteNovenas" to "Novenas favoritas",
            "me.metric.favoriteSaints" to "Santos favoritos",
            "me.metric.favoritePrayers" to "Oraciones favoritas",
            "me.metric.environment" to "Entorno",
            "reminder.novenas" to "Novenas en progreso",
            "reminder.novenasBody" to "Envía recordatorios por la mañana y por la noche cuando tengas una novena en progreso.",
            "reminder.daily" to "Recordatorio diario de Sanctuary",
            "reminder.dailyBody" to "Envía un suave recordatorio matutino cuando no tengas una novena en progreso.",
            "about.title" to "Sobre Sanctuary",
            "about.subtitle" to "Sanctuary es un acompañante católico para la oración, lecturas diarias, santos, vida litúrgica y novenas.",
            "about.desktopVersion" to "Usa Sanctuary en escritorio",
            "about.desktopBody" to "También puedes usar Sanctuary en escritorio para la experiencia web completa, incluyendo lecturas diarias, santos, liturgia, novenas y tu cuenta sincronizada.",
            "about.versionTitle" to "Versión de la app",
            "about.versionLabel" to "Versión",
            "about.buildLabel" to "Compilación",
            "about.environmentLabel" to "Entorno",
            "about.whatsInApp" to "Qué hay en la app",
            "about.references" to "Referencias",
            "about.contact" to "Contacto y comentarios",
            "about.link.desktop" to "Abrir mydailysanctuary.com",
            "about.link.support" to "Soporte",
            "about.link.privacy" to "Política de privacidad",
            "about.whatsInApp.liturgical" to "Litúrgico: vistas de calendario por día, semana y mes con contexto de temporada y enlaces directos a las lecturas diarias.",
            "about.whatsInApp.saints" to "Santos: listados por fecha, perfiles detallados y contenido buscable.",
            "about.whatsInApp.novenas" to "Novenas: fechas de inicio basadas en reglas, seguimiento de fecha final, búsqueda por intenciones y gestión del progreso.",
            "about.referencesBody" to "Sanctuary actualmente hace referencia a estas fuentes públicas para lecturas e información de santos.",
            "about.reference.usccb" to "USCCB (lecturas diarias)",
            "about.reference.wikipedia" to "Wikipedia",
            "about.contactBody" to "Para reportar errores, solicitar correcciones o enviar comentarios, contáctanos e incluye la página o función que estabas usando junto con una breve descripción del problema.",
            "about.emailSupport" to "Enviar correo a soporte",
            "about.supportTitle" to "Soporte",
            "about.privacyTitle" to "Política de privacidad",
            "about.brand" to "Sanctuary",
            "about.link.usccb" to "Lecturas bíblicas diarias de la USCCB",
            "about.link.wikipedia" to "Wikipedia",
            "about.copyright" to "Sanctuary © 2026. Todos los derechos reservados.",
            "about.supportSubtitle" to "Soporte y comentarios para Sanctuary.",
            "about.privacySubtitle" to "Fecha de vigencia: 13 de abril de 2026",
            "about.support.section.help" to "Ayuda y comentarios",
            "about.support.body.help" to "Si necesitas ayuda con Sanctuary, quieres reportar un error o sugerir una mejora, contáctanos en info@mydailysanctuary.com e incluye tu tipo de dispositivo, plataforma y una breve descripción del problema.",
            "about.support.section.features" to "Funciones de la app",
            "about.support.body.features" to "Sanctuary incluye oraciones católicas, novenas, reflexiones de santos, contenido del calendario litúrgico y recordatorios opcionales para acompañar la oración durante el día.",
            "about.support.section.response" to "Tiempo de respuesta",
            "about.support.body.response" to "Hacemos todo lo posible por responder con rapidez a las solicitudes de soporte.",
            "about.privacy.section.collect" to "Información que recopilamos",
            "about.privacy.body.collect" to "Sanctuary está diseñada para funcionar principalmente con contenido local en tu dispositivo. No exigimos crear una cuenta para usar la app.",
            "about.privacy.section.location" to "Ubicación",
            "about.privacy.body.location" to "Si eliges usar funciones con reconocimiento de ubicación, Sanctuary puede solicitar acceso a la ubicación para mejorar el contenido cercano y las experiencias sensibles al tiempo.",
            "about.privacy.section.notifications" to "Notificaciones",
            "about.privacy.body.notifications" to "Si eliges permitir notificaciones, Sanctuary usa permisos de notificación para enviar recordatorios de oración y actividad de novenas. Las notificaciones son opcionales y pueden desactivarse en cualquier momento en la configuración de tu dispositivo.",
            "about.privacy.section.sharing" to "Compartir",
            "about.privacy.body.sharing" to "Sanctuary no vende tu información personal. Usamos proveedores de confianza solo cuando es necesario para respaldar la funcionalidad principal de la app.",
            "about.privacy.section.choices" to "Tus opciones",
            "about.privacy.body.choices" to "Puedes usar la mayor parte de Sanctuary sin crear una cuenta y puedes eliminar los datos de la app de tu dispositivo en cualquier momento.",
            "about.privacy.section.contact" to "Contacto",
            "about.privacy.body.contact" to "Si tienes preguntas sobre privacidad, contáctanos en info@mydailysanctuary.com.",
            "calendar.dailyReadingsTitle" to "Lecturas diarias",
            "calendar.dailyReadingsSubtitle" to "Lecturas de la USCCB dentro de Sanctuary",
            "calendar.chooseDay" to "Elegir día",
            "calendar.dayLabel" to "Día",
            "calendar.dayNumberPrefix" to "Día",
            "calendar.noNovenaStarting" to "Sanctuary no tiene una novena que comience este día.",
            "calendar.noLiturgicalFound" to "No se encontró lectura litúrgica",
            "calendar.noLiturgicalBody" to "Sanctuary todavía no devolvió una observancia litúrgica para este día.",
            "calendar.dailyReadingsMissing" to "Sanctuary no pudo encontrar ahora el enlace de lecturas de la USCCB para hoy.",
            "calendar.dailyReadingsOpenError" to "Sanctuary no pudo abrir ahora las lecturas de hoy.",
            "detail.loadErrorTitle" to "No pudimos cargar esto ahora",
            "detail.loadErrorBody" to "Sanctuary no pudo completar esa solicitud en este momento.",
            "detail.favorite.add" to "Agregar a favoritos",
            "detail.favorite.saved" to "Guardado en favoritos",
            "detail.summary" to "Resumen",
            "detail.biography" to "Biografía",
            "detail.sources" to "Fuentes",
            "detail.intentions" to "Intenciones",
            "detail.startNovena" to "Comenzar novena",
            "detail.stopNovena" to "Detener novena",
            "detail.completeDay" to "Completar día",
            "detail.completed" to "Completada",
            "detail.loginToTrack" to "Inicia sesión o regístrate para comenzar esta novena y seguir tu progreso.",
            "detail.noDayContent" to "Aún no se encontró contenido para este día de la novena.",
            "detail.scripture" to "Escritura",
            "detail.prayer" to "Oración",
            "detail.reflection" to "Reflexión",
            "detail.content" to "Contenido",
            "detail.openingPrayer" to "Oración inicial",
            "detail.meditation" to "Meditación",
            "detail.closingPrayer" to "Oración final",
            "inline.loading" to "Cargando…",
            "season.advent" to "Adviento",
            "season.christmas" to "Navidad",
            "season.lent" to "Cuaresma",
            "season.easter" to "Pascua",
            "season.ordinary" to "Tiempo ordinario"
        )

        val polish = mapOf(
            "tab.home" to "Dom",
            "tab.novenas" to "Nowenny",
            "tab.liturgical" to "Liturgia",
            "tab.saints" to "Święci",
            "tab.me" to "Ja",
            "common.today" to "Dziś",
            "common.day" to "Dzień",
            "common.week" to "Tydzień",
            "common.month" to "Miesiąc",
            "common.close" to "Zamknij",
            "common.cancel" to "Anuluj",
            "common.back" to "Wstecz",
            "common.loading" to "Przygotowywanie Sanctuary...",
            "common.openDetails" to "Otwórz szczegóły",
            "common.search" to "Szukaj",
            "weekday.sun" to "Niedz",
            "weekday.mon" to "Pon",
            "weekday.tue" to "Wt",
            "weekday.wed" to "Śr",
            "weekday.thu" to "Czw",
            "weekday.fri" to "Pt",
            "weekday.sat" to "Sob",
            "home.about" to "O Sanctuary",
            "home.language" to "Język",
            "home.chooseLanguage" to "Wybierz język",
            "home.eyebrow" to "#1 Katolicki Towarzysz Modlitwy",
            "home.welcome" to "Witaj w swoim sanktuarium",
            "home.connect" to "Znajdź czytania dnia, odmów Różaniec albo wyszukaj świętych, nowenny, modlitwy i intencje w opcjach poniżej.",
            "home.supporting" to "Użyj kart, aby przeglądać kalendarz liturgiczny, dni wspomnień świętych i harmonogram nowenn.",
            "home.saints" to "Święci",
            "home.saintsSubtitle" to "Święta i biografie",
            "home.novenas" to "Nowenny",
            "home.novenasSubtitle" to "Drogi modlitwy",
            "home.prayers" to "Modlitwy",
            "home.prayersSubtitle" to "Codzienne podstawy",
            "home.rosary" to "Różaniec",
            "home.rosarySubtitle" to "Tajemnice na każdy dzień",
            "home.daily" to "Codziennie",
            "home.dailySubtitle" to "Czytania dnia",
            "home.intentions" to "Intencje",
            "home.intentionsSubtitle" to "Szukaj według potrzeby",
            "home.liturgical" to "Liturgia",
            "home.liturgicalSubtitle" to "Śledź kalendarz Kościoła",
            "calendar.subtitle.novenas" to "Nowenny • Dotknij, aby przejść",
            "calendar.subtitle.liturgical" to "Liturgia • Dotknij, aby przejść",
            "calendar.subtitle.saints" to "Święci • Dotknij, aby przejść",
            "calendar.searchSaints" to "Szukaj świętych",
            "calendar.searchNovenas" to "Szukaj nowenn",
            "calendar.searchIntentions" to "Szukaj intencji nowenny",
            "calendar.openDailyReadings" to "Otwórz czytania dnia",
            "search.saintsTitle" to "Szukaj świętych",
            "search.novenasTitle" to "Szukaj nowenn",
            "search.prayersTitle" to "Szukaj modlitw",
            "search.rosaryTitle" to "Szukaj różańców",
            "search.intentionsTitle" to "Szukaj intencji nowenny",
            "search.field" to "Szukaj",
            "auth.account" to "Konto",
            "auth.androidTitle" to "Sanctuary na Androida",
            "auth.androidIntro" to "Ta pierwsza wersja Androida skupia się na zgodności logowania i treściach Sanctuary na żywo, abyśmy mogli dziś udostępnić coś prawdziwego na środowisku deweloperskim.",
            "auth.accountBody" to "Zaloguj się lub utwórz konto, aby synchronizować zapisanych świętych, nowenny, modlitwy i postępy.",
            "auth.login" to "Zaloguj się",
            "auth.register" to "Zarejestruj się",
            "auth.signInCalmly" to "Zaloguj się spokojnie",
            "auth.createAccount" to "Utwórz konto",
            "auth.confirmAccount" to "Potwierdź konto",
            "auth.resetCalmly" to "Spokojnie zresetuj hasło",
            "auth.chooseNewPassword" to "Wybierz nowe hasło",
            "auth.email" to "E-mail",
            "auth.password" to "Hasło",
            "auth.confirmPassword" to "Potwierdź hasło",
            "auth.firstName" to "Imię",
            "auth.lastName" to "Nazwisko",
            "auth.code" to "Kod potwierdzenia",
            "auth.forgotPassword" to "Nie pamiętasz hasła?",
            "auth.verificationCode" to "Kod weryfikacyjny",
            "auth.resetCode" to "Kod resetu",
            "auth.newPassword" to "Nowe hasło",
            "auth.confirmNewPassword" to "Potwierdź nowe hasło",
            "auth.back" to "Wstecz",
            "auth.returning" to "Powrót do Sanctuary",
            "auth.returningBody" to "Zaloguj się, aby zsynchronizować zapisanych świętych, nowenny, modlitwy i postęp.",
            "auth.newToSanctuary" to "Nowy w Sanctuary",
            "auth.newToSanctuaryBody" to "Utwórz darmowe konto, aby ta wersja Android mogła synchronizować się z Twoim istniejącym kontem Sanctuary.",
            "auth.createAccountCta" to "Utwórz konto",
            "auth.confirmAccountCta" to "Potwierdź konto",
            "auth.sendNewCode" to "Wyślij nowy kod",
            "auth.sendResetCode" to "Wyślij kod resetu",
            "auth.saveNewPassword" to "Zapisz nowe hasło",
            "auth.sendNewResetCode" to "Wyślij nowy kod resetu",
            "auth.passwordStrength" to "Siła hasła",
            "auth.passwordsMustMatchCreate" to "Hasła muszą się zgadzać przed utworzeniem konta.",
            "auth.passwordsMustMatchSave" to "Hasła muszą się zgadzać przed zapisaniem nowego hasła.",
            "auth.passwordsMatch" to "Hasła są zgodne.",
            "auth.passwordStrengthReady" to "Gotowe",
            "auth.passwordStrengthAlmost" to "Prawie gotowe",
            "auth.passwordStrengthNeedsWork" to "Wymaga pracy",
            "auth.passwordStrengthTooWeak" to "Za słabe",
            "auth.rule.length" to "Co najmniej 10 znaków",
            "auth.rule.upper" to "Jedna wielka litera",
            "auth.rule.lower" to "Jedna mała litera",
            "auth.rule.number" to "Jedna cyfra",
            "auth.confirmationSentPrefix" to "Wysłaliśmy kod potwierdzenia na",
            "auth.resetSentPrefix" to "Wysłaliśmy kod resetu na",
            "status.registerTimeout" to "Sanctuary zbyt długo rejestrowało konto. Spróbuj ponownie.",
            "status.confirmTimeout" to "Sanctuary zbyt długo potwierdzało konto. Spróbuj ponownie.",
            "status.resendTimeout" to "Sanctuary zbyt długo ponownie wysyłało kod potwierdzenia. Spróbuj ponownie.",
            "status.forgotTimeout" to "Sanctuary zbyt długo rozpoczynało reset hasła. Spróbuj ponownie.",
            "status.resetTimeout" to "Sanctuary zbyt długo resetowało hasło. Spróbuj ponownie.",
            "status.loginTimeout" to "Sanctuary zbyt długo logowało Cię. Spróbuj ponownie.",
            "status.deleteAccountTimeout" to "Usuwanie konta w Sanctuary trwało zbyt długo. Spróbuj ponownie.",
            "status.deleteAccountFailed" to "Nie można teraz usunąć konta. Spróbuj ponownie.",
            "status.remindersUpdated" to "Twoje preferencje przypomnień zostały zaktualizowane.",
            "status.remindersOff" to "Przypomnienia modlitewne są wyłączone.",
            "me.title" to "Ja",
            "me.subtitle" to "Twoje nowenny w toku i zapisane ulubione.",
            "me.signedIn" to "Zalogowano",
            "me.accountSummary" to "Tutaj znajdziesz ulubione, aktywne nowenny i przyszłe ustawienia konta.",
            "me.accountFallback" to "Konto Sanctuary",
            "me.reminders" to "Przypomnienia",
            "me.inProgress" to "Nowenny w toku",
            "me.favoriteNovenas" to "Ulubione nowenny",
            "me.favoriteSaints" to "Ulubieni święci",
            "me.favoritePrayers" to "Ulubione modlitwy",
            "me.noInProgress" to "Brak nowenn w toku.",
            "me.noneFavoriteNovenas" to "Brak ulubionych nowenn.",
            "me.noneFavoriteSaints" to "Brak ulubionych świętych.",
            "me.noneFavoritePrayers" to "Brak ulubionych modlitw.",
            "me.logout" to "Wyloguj",
            "me.deleteAccount.title" to "Usuń konto",
            "me.deleteAccount.body" to "Trwale usuń konto Sanctuary, ulubione elementy, postęp nowenn i preferencje.",
            "me.deleteAccount.action" to "Usuń moje konto",
            "me.deleteAccount.deleting" to "Usuwanie konta...",
            "me.deleteAccount.confirmTitle" to "Usunąć konto?",
            "me.deleteAccount.confirmBody" to "To trwale usunie konto Sanctuary i zapisane dane aplikacji. Tej operacji nie można cofnąć.",
            "me.deleteAccount.confirmAction" to "Usuń konto",
            "me.metric.activeNovenas" to "Aktywne nowenny",
            "me.metric.favoriteNovenas" to "Ulubione nowenny",
            "me.metric.favoriteSaints" to "Ulubieni święci",
            "me.metric.favoritePrayers" to "Ulubione modlitwy",
            "me.metric.environment" to "Środowisko",
            "reminder.novenas" to "Nowenny w toku",
            "reminder.novenasBody" to "Wysyłaj poranne i wieczorne przypomnienia, gdy masz aktywną nowennę.",
            "reminder.daily" to "Codzienne przypomnienie Sanctuary",
            "reminder.dailyBody" to "Wysyłaj delikatne poranne przypomnienie, gdy nie masz aktywnej nowenny.",
            "about.title" to "O Sanctuary",
            "about.subtitle" to "Sanctuary to katolicki towarzysz modlitwy, codziennych czytań, świętych, życia liturgicznego i nowenn.",
            "about.desktopVersion" to "Użyj Sanctuary na komputerze",
            "about.desktopBody" to "Możesz też używać Sanctuary na komputerze, aby uzyskać pełne doświadczenie webowe, w tym codzienne czytania, świętych, liturgię, nowenny i zsynchronizowane konto.",
            "about.versionTitle" to "Wersja aplikacji",
            "about.versionLabel" to "Wersja",
            "about.buildLabel" to "Kompilacja",
            "about.environmentLabel" to "Środowisko",
            "about.whatsInApp" to "Co jest w aplikacji",
            "about.references" to "Źródła",
            "about.contact" to "Kontakt i opinie",
            "about.link.desktop" to "Otwórz mydailysanctuary.com",
            "about.link.support" to "Wsparcie",
            "about.link.privacy" to "Polityka prywatności",
            "about.whatsInApp.liturgical" to "Liturgia: widoki kalendarza dnia, tygodnia i miesiąca z kontekstem sezonu i bezpośrednimi linkami do codziennych czytań.",
            "about.whatsInApp.saints" to "Święci: listy powiązane z datami, szczegółowe profile i przeszukiwalna treść.",
            "about.whatsInApp.novenas" to "Nowenny: daty rozpoczęcia oparte na regułach, śledzenie daty zakończenia, wyszukiwanie intencji i zarządzanie postępem.",
            "about.referencesBody" to "Sanctuary obecnie korzysta z tych publicznych źródeł dla czytań i informacji o świętych.",
            "about.reference.usccb" to "USCCB (codzienne czytania)",
            "about.reference.wikipedia" to "Wikipedia",
            "about.contactBody" to "Aby zgłosić błąd, poprosić o poprawkę lub wysłać opinię, skontaktuj się z nami i dołącz stronę lub funkcję, której używałeś, wraz z krótkim opisem problemu.",
            "about.emailSupport" to "Napisz do wsparcia",
            "about.supportTitle" to "Wsparcie",
            "about.privacyTitle" to "Polityka prywatności",
            "about.brand" to "Sanctuary",
            "about.link.usccb" to "Codzienne czytania biblijne USCCB",
            "about.link.wikipedia" to "Wikipedia",
            "about.copyright" to "Sanctuary © 2026. Wszelkie prawa zastrzeżone.",
            "about.supportSubtitle" to "Wsparcie i opinie dla Sanctuary.",
            "about.privacySubtitle" to "Data wejścia w życie: 13 kwietnia 2026",
            "about.support.section.help" to "Pomoc i opinie",
            "about.support.body.help" to "Jeśli potrzebujesz pomocy z Sanctuary, chcesz zgłosić błąd lub zasugerować ulepszenie, skontaktuj się z nami pod adresem info@mydailysanctuary.com i dołącz typ urządzenia, platformę oraz krótki opis problemu.",
            "about.support.section.features" to "Funkcje aplikacji",
            "about.support.body.features" to "Sanctuary zawiera katolickie modlitwy, nowenny, refleksje o świętych, treści kalendarza liturgicznego oraz opcjonalne przypomnienia wspierające modlitwę w ciągu dnia.",
            "about.support.section.response" to "Czas odpowiedzi",
            "about.support.body.response" to "Dokładamy wszelkich starań, aby szybko odpowiadać na prośby o wsparcie.",
            "about.privacy.section.collect" to "Jakie informacje zbieramy",
            "about.privacy.body.collect" to "Sanctuary zostało zaprojektowane tak, aby działać głównie na lokalnych treściach na Twoim urządzeniu. Nie wymagamy tworzenia konta, aby korzystać z aplikacji.",
            "about.privacy.section.location" to "Lokalizacja",
            "about.privacy.body.location" to "Jeśli zdecydujesz się używać funkcji zależnych od lokalizacji, Sanctuary może poprosić o dostęp do lokalizacji, aby ulepszyć pobliskie treści i doświadczenia zależne od czasu.",
            "about.privacy.section.notifications" to "Powiadomienia",
            "about.privacy.body.notifications" to "Jeśli zgodzisz się na powiadomienia, Sanctuary używa odpowiednich uprawnień do wysyłania przypomnień o modlitwie i aktywności nowenn. Powiadomienia są opcjonalne i można je wyłączyć w ustawieniach urządzenia.",
            "about.privacy.section.sharing" to "Udostępnianie",
            "about.privacy.body.sharing" to "Sanctuary nie sprzedaje Twoich danych osobowych. Korzystamy z zaufanych dostawców tylko tam, gdzie jest to potrzebne do działania podstawowych funkcji aplikacji.",
            "about.privacy.section.choices" to "Twoje wybory",
            "about.privacy.body.choices" to "Możesz korzystać z większości funkcji Sanctuary bez tworzenia konta i w dowolnym momencie usunąć dane aplikacji z urządzenia.",
            "about.privacy.section.contact" to "Kontakt",
            "about.privacy.body.contact" to "Jeśli masz pytania dotyczące prywatności, skontaktuj się z nami pod adresem info@mydailysanctuary.com.",
            "calendar.dailyReadingsTitle" to "Czytania dzienne",
            "calendar.dailyReadingsSubtitle" to "Czytania USCCB w Sanctuary",
            "calendar.chooseDay" to "Wybierz dzień",
            "calendar.dayLabel" to "Dzień",
            "calendar.dayNumberPrefix" to "Dzień",
            "calendar.noNovenaStarting" to "Sanctuary nie ma nowenny rozpoczynającej się tego dnia.",
            "calendar.noLiturgicalFound" to "Nie znaleziono czytania liturgicznego",
            "calendar.noLiturgicalBody" to "Sanctuary nie zwróciło jeszcze obserwancji liturgicznej dla tego dnia.",
            "calendar.dailyReadingsMissing" to "Sanctuary nie mogło teraz znaleźć dzisiejszego linku do czytań USCCB.",
            "calendar.dailyReadingsOpenError" to "Sanctuary nie mogło teraz otworzyć dzisiejszych czytań.",
            "detail.loadErrorTitle" to "Nie udało się teraz tego załadować",
            "detail.loadErrorBody" to "Sanctuary nie mogło teraz ukończyć tego żądania.",
            "detail.favorite.add" to "Dodaj do ulubionych",
            "detail.favorite.saved" to "Zapisano w ulubionych",
            "detail.summary" to "Podsumowanie",
            "detail.biography" to "Biografia",
            "detail.sources" to "Źródła",
            "detail.intentions" to "Intencje",
            "detail.startNovena" to "Rozpocznij nowennę",
            "detail.stopNovena" to "Zatrzymaj nowennę",
            "detail.completeDay" to "Ukończ dzień",
            "detail.completed" to "Ukończono",
            "detail.loginToTrack" to "Zaloguj się lub zarejestruj, aby rozpocząć tę nowennę i śledzić postęp.",
            "detail.noDayContent" to "Nie znaleziono jeszcze treści dla tego dnia nowenny.",
            "detail.scripture" to "Pismo",
            "detail.prayer" to "Modlitwa",
            "detail.reflection" to "Refleksja",
            "detail.content" to "Treść",
            "detail.openingPrayer" to "Modlitwa otwierająca",
            "detail.meditation" to "Medytacja",
            "detail.closingPrayer" to "Modlitwa końcowa",
            "inline.loading" to "Ładowanie…",
            "season.advent" to "Adwent",
            "season.christmas" to "Boże Narodzenie",
            "season.lent" to "Wielki Post",
            "season.easter" to "Wielkanoc",
            "season.ordinary" to "Okres zwykły"
        )
    }
}

val LocalSanctuaryStrings = staticCompositionLocalOf { SanctuaryStrings(AppLanguage.English) }

@Composable
fun sanctuaryStrings(): SanctuaryStrings = LocalSanctuaryStrings.current
